/*
 * Peer Side
 * This project is being developed by Pablo Martinez and Xavi Moreno
 */

package ub.view.views;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import javax.swing.JFrame;
import ub.common.UserInUseException;

/**
 *
 * @author zenbook
 */
public class WelcomeView extends JFrame {

    private String IP;
    private int port;
    
    /**
     * Creates new form NewJFrame
     * @param IP
     * @param port
     */
    public WelcomeView(String IP, int port) {
        initComponents();
        this.IP = IP;
        this.port = port;
        lbl_nickname_in_use.setVisible(false);
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((screen.getWidth() - getWidth()) /2);
        int y = (int) ((screen.getHeight() -getHeight()) /2);
        setLocation(x, y); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nickname = new javax.swing.JLabel();
        tf_nickname = new javax.swing.JTextField();
        btn_proceed = new javax.swing.JButton();
        lbl_nickname_in_use = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RMI Chat");
        setResizable(false);

        lbl_nickname.setText("Nickname");

        tf_nickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nicknameActionPerformed(evt);
            }
        });

        btn_proceed.setText("Proceed");
        btn_proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proceedActionPerformed(evt);
            }
        });

        lbl_nickname_in_use.setForeground(new java.awt.Color(255, 12, 0));
        lbl_nickname_in_use.setText("That nickname its in use!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_nickname_in_use)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_proceed))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_nickname, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nickname)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nickname)
                    .addComponent(tf_nickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_proceed)
                    .addComponent(lbl_nickname_in_use))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_nicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nicknameActionPerformed
        initApp(tf_nickname.getText());
    }//GEN-LAST:event_tf_nicknameActionPerformed

    private void btn_proceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proceedActionPerformed
        initApp(tf_nickname.getText());
    }//GEN-LAST:event_btn_proceedActionPerformed

    private void initApp(final String user) {
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    ChatView c = new ChatView();
                    c.registry(IP,port,  user);
                    c.setVisible(true);
                    setVisible(false);
                    dispose();
                } catch (RemoteException | MalformedURLException | NotBoundException ex) {
                    lbl_nickname_in_use.setText("Server is down");
                    lbl_nickname_in_use.setVisible(true);
                    tf_nickname.setText("");
                } catch (UserInUseException ex) {
                    lbl_nickname_in_use.setVisible(true);
                    tf_nickname.setText("");
                }
                    
            }
        });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        if(args.length != 2) {
            System.out.println("Execute: java -jar <ip> <port>");
            System.exit(0);
        }
        int p = 0;
        
        try{
             p = Integer.parseInt(args[1]);
        }catch(NumberFormatException ex) {
            System.out.println("Port must be a integer");
            System.exit(0);
        }
        
        if(p<1024 || p > 65535) {
            System.out.println("Port must be between 1024 and 65535, both included");
            System.exit(0);
        }
        
        final String IP = args[0];
        final int port = p;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new WelcomeView(IP,port).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_proceed;
    private javax.swing.JLabel lbl_nickname;
    private javax.swing.JLabel lbl_nickname_in_use;
    private javax.swing.JTextField tf_nickname;
    // End of variables declaration//GEN-END:variables
}
