/*
 * Peer Side
 * This project is being developed by Pablo Martinez and Xavi Moreno
 */

package ub.view;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.concurrent.ConcurrentHashMap;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;

/**
 *
 * @author zenbook
 */
public class ChatView extends JFrame {

    private ConcurrentHashMap<Long, MessageBox> chats;
    private MessageBox currentMessageBox;
    
    /**
     * Creates new form ChatView
     */
    public ChatView() {
        initComponents();
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((screen.getWidth() - getWidth()) /2);
        int y = (int) ((screen.getHeight() -getHeight()) /2);
        setLocation(x, y);
        
        btn_send.setVisible(false);
        tf_send.setVisible(false);
        tab_chats.setVisible(false);
        
        list_users.setModel(new DefaultListModel());
        list_groups.setModel(new DefaultListModel());
        
        DefaultListCellRenderer renderer =  (DefaultListCellRenderer)list_groups.getCellRenderer();  
        renderer.setHorizontalAlignment(JLabel.CENTER); 
        renderer = (DefaultListCellRenderer)list_users.getCellRenderer();  
        renderer.setHorizontalAlignment(JLabel.CENTER); 
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                
            }
        });
        
        currentMessageBox = null;
        
        
        addUser("Xavi");
        addUser("falcon");
        addUser("Xavi");
        addUser("falcon");
        addUser("Xavi");
        addUser("falcon");
        addUser("Xavi");
        addUser("falcon");
        addUser("Xavi");
        addUser("falcon");
        addUser("Xavi");
        addUser("falcon");
        addUser("Xavi");
        addUser("falcon");
        addUser("Xavi");
        addUser("falcon");
        addUser("Xavi");
        addUser("falcon");
        addUser("Xavi");
        addUser("falcon");
        addUser("Xavi");
        addUser("falcon");
        addUser("Xavi");
        addUser("falcon");
        addUser("Xavi");
        addUser("falcon");
        addGroup("Perrillas");
        addGroup("Playa!");
        addGroup("Familia");
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab_chats = new javax.swing.JTabbedPane();
        btn_send = new javax.swing.JButton();
        tf_send = new javax.swing.JTextField();
        tab_users = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_users = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_groups = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat RMI");

        btn_send.setText("Send");

        tab_users.setBorder(null);
        tab_users.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        list_users.setBorder(null);
        list_users.setFont(new java.awt.Font("DejaVu Sans Mono", 2, 15)); // NOI18N
        list_users.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        list_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                list_usersMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(list_users);

        tab_users.addTab("Users", jScrollPane1);

        list_groups.setBorder(null);
        list_groups.setFont(new java.awt.Font("DejaVu Sans Mono", 2, 15)); // NOI18N
        list_groups.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        list_groups.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                list_groupsMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(list_groups);

        tab_users.addTab("Groups", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab_users, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tf_send, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_send, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tab_chats))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tab_chats)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_send)
                            .addComponent(tf_send, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tab_users, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void list_groupsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_groupsMousePressed
        if(evt.getClickCount() == 2) {
            
        }
    }//GEN-LAST:event_list_groupsMousePressed

    private void list_usersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_usersMousePressed
        DefaultListModel model = (DefaultListModel) list_users.getModel();
        String name = (String) model.get(list_users.getSelectedIndex());
        if(evt.getClickCount() == 2) {
            addTab(name, false);
        }
    }//GEN-LAST:event_list_usersMousePressed

    private void addTab(String name, boolean group) {
        if(tab_chats.getTabCount() == 0) {
            btn_send.setVisible(true);
            tf_send.setVisible(true);
            tab_chats.setVisible(true);
        }
        tab_chats.addTab(name, new MessageBox("Xavi", name));
        tab_chats.setSelectedIndex(tab_chats.getTabCount()-1);
    }
    
    private void addUser(String user) {
        addStringInList(user, list_users);
    }
    
    private void addGroup(String group) {
        addStringInList(group, list_groups);
    }
    
    private void addStringInList(String string, JList list) {
        DefaultListModel model = (DefaultListModel) list.getModel();
        model.addElement(string);
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_send;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList list_groups;
    private javax.swing.JList list_users;
    private javax.swing.JTabbedPane tab_chats;
    private javax.swing.JTabbedPane tab_users;
    private javax.swing.JTextField tf_send;
    // End of variables declaration//GEN-END:variables
}
